/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AsPartsRouteImport } from './routes/as-parts'
import { Route as ModelRouteImport } from './routes/$model'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CsS8RouteImport } from './routes/cs.s8'
import { Route as CsS7RouteImport } from './routes/cs.s7'
import { Route as CsS6RouteImport } from './routes/cs.s6'
import { Route as CsS5RouteImport } from './routes/cs.s5'
import { Route as CsS4RouteImport } from './routes/cs.s4'
import { Route as CsS3RouteImport } from './routes/cs.s3'
import { Route as CsS2RouteImport } from './routes/cs.s2'
import { Route as CsS1RouteImport } from './routes/cs.s1'

const AsPartsRoute = AsPartsRouteImport.update({
  id: '/as-parts',
  path: '/as-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/$model',
  path: '/$model',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CsS8Route = CsS8RouteImport.update({
  id: '/cs/s8',
  path: '/cs/s8',
  getParentRoute: () => rootRouteImport,
} as any)
const CsS7Route = CsS7RouteImport.update({
  id: '/cs/s7',
  path: '/cs/s7',
  getParentRoute: () => rootRouteImport,
} as any)
const CsS6Route = CsS6RouteImport.update({
  id: '/cs/s6',
  path: '/cs/s6',
  getParentRoute: () => rootRouteImport,
} as any)
const CsS5Route = CsS5RouteImport.update({
  id: '/cs/s5',
  path: '/cs/s5',
  getParentRoute: () => rootRouteImport,
} as any)
const CsS4Route = CsS4RouteImport.update({
  id: '/cs/s4',
  path: '/cs/s4',
  getParentRoute: () => rootRouteImport,
} as any)
const CsS3Route = CsS3RouteImport.update({
  id: '/cs/s3',
  path: '/cs/s3',
  getParentRoute: () => rootRouteImport,
} as any)
const CsS2Route = CsS2RouteImport.update({
  id: '/cs/s2',
  path: '/cs/s2',
  getParentRoute: () => rootRouteImport,
} as any)
const CsS1Route = CsS1RouteImport.update({
  id: '/cs/s1',
  path: '/cs/s1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$model': typeof ModelRoute
  '/as-parts': typeof AsPartsRoute
  '/cs/s1': typeof CsS1Route
  '/cs/s2': typeof CsS2Route
  '/cs/s3': typeof CsS3Route
  '/cs/s4': typeof CsS4Route
  '/cs/s5': typeof CsS5Route
  '/cs/s6': typeof CsS6Route
  '/cs/s7': typeof CsS7Route
  '/cs/s8': typeof CsS8Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$model': typeof ModelRoute
  '/as-parts': typeof AsPartsRoute
  '/cs/s1': typeof CsS1Route
  '/cs/s2': typeof CsS2Route
  '/cs/s3': typeof CsS3Route
  '/cs/s4': typeof CsS4Route
  '/cs/s5': typeof CsS5Route
  '/cs/s6': typeof CsS6Route
  '/cs/s7': typeof CsS7Route
  '/cs/s8': typeof CsS8Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$model': typeof ModelRoute
  '/as-parts': typeof AsPartsRoute
  '/cs/s1': typeof CsS1Route
  '/cs/s2': typeof CsS2Route
  '/cs/s3': typeof CsS3Route
  '/cs/s4': typeof CsS4Route
  '/cs/s5': typeof CsS5Route
  '/cs/s6': typeof CsS6Route
  '/cs/s7': typeof CsS7Route
  '/cs/s8': typeof CsS8Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$model'
    | '/as-parts'
    | '/cs/s1'
    | '/cs/s2'
    | '/cs/s3'
    | '/cs/s4'
    | '/cs/s5'
    | '/cs/s6'
    | '/cs/s7'
    | '/cs/s8'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$model'
    | '/as-parts'
    | '/cs/s1'
    | '/cs/s2'
    | '/cs/s3'
    | '/cs/s4'
    | '/cs/s5'
    | '/cs/s6'
    | '/cs/s7'
    | '/cs/s8'
  id:
    | '__root__'
    | '/'
    | '/$model'
    | '/as-parts'
    | '/cs/s1'
    | '/cs/s2'
    | '/cs/s3'
    | '/cs/s4'
    | '/cs/s5'
    | '/cs/s6'
    | '/cs/s7'
    | '/cs/s8'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelRoute: typeof ModelRoute
  AsPartsRoute: typeof AsPartsRoute
  CsS1Route: typeof CsS1Route
  CsS2Route: typeof CsS2Route
  CsS3Route: typeof CsS3Route
  CsS4Route: typeof CsS4Route
  CsS5Route: typeof CsS5Route
  CsS6Route: typeof CsS6Route
  CsS7Route: typeof CsS7Route
  CsS8Route: typeof CsS8Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/as-parts': {
      id: '/as-parts'
      path: '/as-parts'
      fullPath: '/as-parts'
      preLoaderRoute: typeof AsPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$model': {
      id: '/$model'
      path: '/$model'
      fullPath: '/$model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs/s8': {
      id: '/cs/s8'
      path: '/cs/s8'
      fullPath: '/cs/s8'
      preLoaderRoute: typeof CsS8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs/s7': {
      id: '/cs/s7'
      path: '/cs/s7'
      fullPath: '/cs/s7'
      preLoaderRoute: typeof CsS7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs/s6': {
      id: '/cs/s6'
      path: '/cs/s6'
      fullPath: '/cs/s6'
      preLoaderRoute: typeof CsS6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs/s5': {
      id: '/cs/s5'
      path: '/cs/s5'
      fullPath: '/cs/s5'
      preLoaderRoute: typeof CsS5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs/s4': {
      id: '/cs/s4'
      path: '/cs/s4'
      fullPath: '/cs/s4'
      preLoaderRoute: typeof CsS4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs/s3': {
      id: '/cs/s3'
      path: '/cs/s3'
      fullPath: '/cs/s3'
      preLoaderRoute: typeof CsS3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs/s2': {
      id: '/cs/s2'
      path: '/cs/s2'
      fullPath: '/cs/s2'
      preLoaderRoute: typeof CsS2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs/s1': {
      id: '/cs/s1'
      path: '/cs/s1'
      fullPath: '/cs/s1'
      preLoaderRoute: typeof CsS1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelRoute: ModelRoute,
  AsPartsRoute: AsPartsRoute,
  CsS1Route: CsS1Route,
  CsS2Route: CsS2Route,
  CsS3Route: CsS3Route,
  CsS4Route: CsS4Route,
  CsS5Route: CsS5Route,
  CsS6Route: CsS6Route,
  CsS7Route: CsS7Route,
  CsS8Route: CsS8Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
